resourcestring                                     {deutsch}

  capForm='PV-Archiv - Version 03/2023';
  capArch='Archivieren';
  hntArch='Alle Dateien einlesen und monatlich zusammenfassen um Anzahl der Dateien zu reduzieren.';
  capProt='Protokoll speichern';
  hntProt='Die Protokollausgabe in eine Textdatei speichern.';
  capClose='Beenden';
  hntClose='Programm beenden.';
  hntArchDir='Pfad zum lokalen Datenverzeichnis (Kopie Datawarehouse).';
  hntMask='Filter der Dateinamen im Datawarehouse. Test des Filters mit "T".';

  fn_proto='_Protokoll_1.txt';

  resFilesFound=' Dateien gefunden';
  resCreated=' angelegt';
  resSaved=' gespeichert';
  resWith=' mit ';
  resIn=' in ';
  resDatasets=' Datensätzen';
  resFiles=' Dateien';
  errFileName='Dateinamen passen nicht.';
  errSettings='Settings fehlerhaft oder fehlen ganz';
  errArchDir='Temporäres Archivierungsverzeichnis konnte nicht angelegt werden.';
  errFirstday=' startet nicht mit dem 01. Tag des Monats. Datei wird nicht angelegt.';
  errLck=' enthält Lücken. Datei sollte nicht benutzt werden.';

