resourcestring                                     {english}

  capForm='PV-Archive - version 03/2023';
  capArch='Archive';
  hntArch='Read all files and compress to monthly files to reduce amount of files.';
  capProt='Save protocol';
  hntProt='Save protocol output to text file.';
  capClose='Quit';
  hntClose='Close the application';
  hntArchDir='Path to local data files (Copy of Datawarehouse).';
  hntMask='Filter for file names in Datawarehouse. Test filter by "T".';

  fn_proto='_protocol_1.txt';

  resFilesFound=' files found';
  resCreated=' created';
  resSaved=' saved';
  resWith=' with ';
  resIn=' at ';
  resDatasets=' datasets';
  resFiles=' files';
  errFileName='Wrong filenames';
  errSettings='Wrong or missing settings';
  errArchDir='Temporary folder for arcived files cound not be created.';
  errFirstday=' does not start with 01. day of month. File will not be created.';
  errLck=' contains gaps. File should not be used.';

